build:
  hugo:
    image: golang:1.5
    environment:
      - HUGO=0.15_linux_amd64
    commands:
      - curl -L -o /tmp/hugo_$HUGO.tar.gz https://github.com/spf13/hugo/releases/download/v0.15/hugo_$HUGO.tar.gz
      - tar xvf /tmp/hugo_$HUGO.tar.gz -C /tmp/
      - mv /tmp/hugo_$HUGO/hugo_$HUGO /usr/bin/hugo
      - mkdir ../gh-pages
      - hugo -d ../gh-pages
    when:
      branch: tea-ci

  push:
    image: golang:1.5
    commands:
      - ls
      - ls ..
      - git checkout --orphan gh-pages-local
      - git rm --cache -r .
      - cp ../gh-pages/* -r .
      - git add .
      - git commit -a -m "Github pages auto update." --author="Tea CI< teaci-docs@users.noreply.github.com>"
      - echo machine github.com > ~/.netrc
      - echo         login $$USER >> ~/.netrc
      - echo         password $$PASS >> ~/.netrc
      - git push -f origin gh-pages-local:gh-pages

    when:
      branch: tea-ci
